<a href="https://colab.research.google.com/github/hewp84/CRT420/blob/main/Numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Topic 1: Numpy, part 1

NumPy is a fundamental package for scientific computing in Python. It provides support for large, multi-dimensional arrays and matrices along with a large library of high-level mathematical functions to operate on these arrays.

Some key features of NumPy include:

* NumPy Arrays

    * Creating arrays
    * Array indexing
    * Basic array operations (arithmetic, comparisons, etc)
    * Array reshaping and transposing
    * Broadcasting
* Advanced Array Functionality

    * Masked arrays
    * Array concatenation and splitting
    * Sorting arrays
    * Unique elements, set operations
    * Random number generation with arrays
* Linear Algebra Functions

    * Vector/matrix math (dot product, determinants, inverses etc)
    * Decompositions (LU, QR, SVD etc)
    * Eigenvalues and eigenvectors
* Statistical Functions

    * Mean, median, variance etc of array
    * Histogramming
    * Correlations
    * Distributions (PDFs, CDFs)
* Input/Output

    * Loading and saving arrays to disk
    * Reading/writing specific file formats like CSV
    * Memory mapping for large arrays

## Numpy Arrays

The main object in NumPy is the homogeneous multidimensional array. This is a table of elements all of the same type (e.g. float64, int32) indexed by a tuple of positive integers.

Creating arrays:

* np.array(): Create arrays from python lists or tuples
* np.zeros(): Create arrays filled with zeros
* np.ones(): Create arrays filled with ones
* np.full(): Create arrays filled with any value
* np.arange(): Like python range but returns array
* np.linspace(): Create arrays with evenly spaced elements

In [55]:
import numpy as np

a = np.array([1, 2, 3, 4]) # Create 1D array

b = np.array([[1, 2], [3, 4]]) # 2D array
#print(b)

c = np.zeros(3) # [0. 0. 0.]

d = np.ones((2,3), dtype=int) # [[1 1 1] 
                              #  [1 1 1]]
e = np.full((3,2), 7) # [[7 7]
                       #  [7 7] 
                       #  [7 7]]

f = np.arange(5) # [0 1 2 3 4]
g = np.linspace(0, 1, 5) # [0.  0.25 0.5  0.75 1.  ]
print(g)

[0.   0.25 0.5  0.75 1.  ]


Array indexing:

* 1D arrays indexed like python lists
* 2D indexed using [row, column]
* Fancy indexing with boolean masks, ranges, etc.

In [57]:
a = np.array([1, 2, 3, 4]) 
a[0] # 1
a[-1] # 4

b = np.array([[1,2,3], [4,5,6]])  
b[0, 0] # 1
b[1, -1] # 6

c = np.array([1, 5, 2, 18, 4])
c[c < 5] # [1, 2, 4]


array([1, 2, 4])

In [58]:
arr = np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [59]:
# Select elements greater than 5
mask = arr > 5  
arr[mask] 

# Output: array([6, 7, 8, 9, 10])

array([ 6,  7,  8,  9, 10])

In [62]:
# Select range of elements from index 1 to 5
arr[1:3]

# Output: array([2, 3, 4, 5])

array([2, 3])

In [65]:
# Select elements between 3 and 7
mask = (arr >= 3) & (arr <= 7)
arr[mask]  

# Output: array([3, 4, 5, 6, 7])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
# Select elements at indices 1, 3 and 5
indices = [1, 3, 5]
arr[indices]

# Output: array([2, 4, 6])

array([2, 4, 6])

In [67]:
# Select values greater than 7
i = np.where(arr > 7) 
arr[i]

# Output: array([8, 9, 10])

array([ 8,  9, 10])

In [95]:
text = np.array(['Brock','Liz','Ron'])
print(text)

['Brock' 'Liz' 'Ron']


## Mathematics with Numpy

### Arithmetic operations with Arrays

In [77]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [78]:
a + b
a - b
a * b
a / b




array([0.25, 0.4 , 0.5 ])

In [79]:
np.dot(a, b)

32

In [80]:
c = np.array([[1, 1], [0, 1]]) 
d = np.array([[2, 0], [3, 4]])

np.matmul(c, d)


array([[5, 4],
       [3, 4]])

### Algebra & Trigonometry:

* np.sin(), np.cos(), np.tan() - Trigonometry
* np.log(), np.exp() - Logarithms/Exponentiation
* np.sqrt(), np.power() - Roots/Powers
* np.maximum(), np.minimum() - Element-wise maximum/minimum



In [81]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

### Linear algebra:

* np.linalg module - Matrix decompositions, determinants, etc.

In [ ]:
values = np.linspace(0, np.pi, 3)
np.sin(values) 

np.linalg.det(c) # 1.0
np.linalg.eig(d) # Eigendecomposition

### Statistics

* Mininum and maximum: .min(), .max()
* Central tendency measurements: .mean(), np.median(arr)
* Dispersion measurments: .var(), .std(), np.quantile(arr, 0.25)
* Correlation, and histograms: np.corrcoef(arr1, arr2), np.histogram(arr, bins= #)

In [93]:
stat = np.array([1, 2, 3, 4, 5])
stat.mean()
stat.std()

1.4142135623730951

In [ ]:
arr.min() 
np.histogram(arr, bins= 5)

## Applications with Numpy

### Image Processing

NumPy is used for storing and manipulating image pixel data. Images in Python can be represented as NumPy arrays for efficient storage and vectorized processing. Operations like filtering, transformations, masking, etc. can be applied to images using NumPy array operations.

In [ ]:
#Filters used for Image processing with Numpy

# Median filter - Help reduce noise/speckles
from scipy.ndimage import median_filter
median_filtered = median_filter(img_array, size=3)

# Sobel filter - Detect edges/gradients
from scipy.ndimage import sobel
sobel_filtered = sobel(img_array)

# Prewitt filter - Also detects edges
from scipy.ndimage import prewitt
prewitt_filtered = prewitt(img_array)

# Gaussian high-pass filter - Sharpen image
from scipy.ndimage import gaussian_filter
sharpened = img_array - gaussian_filter(img_array, sigma=10)

# Laplacian filter - Also used for sharpening
from scipy.ndimage import laplace
laplace_filtered = laplace(img_array)

# Histogram equalization - Improve contrast
from scipy import signal
equalized = signal.histeq(img_array)

In [ ]:
#Algorithm
import numpy as np
from PIL import Image

# Load image and convert to NumPy array
img = Image.open('encapsulation.png')
img_array = np.asarray(img) 

# Apply Gaussian blur filter
from scipy.ndimage import gaussian_filter 
blurred = gaussian_filter(img_array, sigma=5)

# Save blurred image 
blurred_img = Image.fromarray(blurred)
blurred_img.save('blurred.jpg')