<a href="https://colab.research.google.com/github/hewp84/CRT420/blob/main/Numpy_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Topic 1: Numpy, part 2

## Inputs / Outputs

In [33]:
import numpy as np

np.genfromtxt allows loading data from a file into a NumPy array. For example loading from a CSV file:

In [36]:
data = np.genfromtxt('sample.csv', delimiter=',')

In [37]:
data

array([[ nan,  nan,  nan,  nan,  nan],
       [  0.,  96.,  73.,   1., 247.],
       [  1.,  38., 348.,   1., 160.],
       [  2.,  87., 256.,   2., 248.],
       [  3., 114., 141.,   2., 112.],
       [  4.,  76., 132.,   2., 134.],
       [  5.,  69., 331.,   1., 137.],
       [  6.,  93.,  53.,   2., 287.],
       [  7.,  18., 169.,   2., 157.],
       [  8.,   4., 178.,   1., 110.],
       [  9.,  40., 144.,   1., 159.],
       [ 10., 105., 203.,   2., 280.],
       [ 11.,  51., 127.,   1., 214.],
       [ 12.,  50.,  63.,   2., 161.],
       [ 13.,  48., 190.,   2., 157.],
       [ 14.,  70.,  80.,   2., 258.],
       [ 15.,  69., 130.,   2., 253.],
       [ 16., 107., 309.,   1., 123.],
       [ 17.,  95., 306.,   1., 149.],
       [ 18.,   8., 320.,   1., 266.],
       [ 19.,  26.,  62.,   2., 263.],
       [ 20.,  76.,  72.,   2., 227.],
       [ 21.,  16.,  54.,   1., 181.],
       [ 22.,  92., 350.,   1., 174.],
       [ 23.,  66.,  81.,   1., 237.],
       [ 24.,   4., 334.,

#### Mostly used key arguments

* fname: File path
* delimiter: Character separating values
* skip_header: Number of rows to skip at top
* missing_values: Value indicating missing data
* usecols: Columns to read from file
* dtype: Data type of array

For example, loading specific columns from a CSV with headers:

In [43]:
data = np.genfromtxt('sample.csv', delimiter=',', skip_header=1, dtype=int)

### Operations with columns

* Central Tendency measures
* Sorting .sort()
* Filtering using boolean masks
* Math operations with column arrays

In [44]:
age = data[:,1]
age

array([ 96,  38,  87, 114,  76,  69,  93,  18,   4,  40, 105,  51,  50,
        48,  70,  69, 107,  95,   8,  26,  76,  16,  92,  66,   4,  67,
        94,  64, 113,  66,  58, 105,  44,  23,  78,  51,  38, 107, 116,
        42,  69,  19,  30,  11, 110,  15,   3, 110,  78,  37,   5,  51,
         7,  71,  96,  39,  71,  78,  37,  41, 106, 116,  71,  21,  46,
         9, 108,  66,   4])

In [47]:
age.sort()


array([  3,   4,   4,   4,   5,   7,   8,   9,  11,  15,  16,  18,  19,
        21,  23,  26,  30,  37,  37,  38,  38,  39,  40,  41,  42,  44,
        46,  48,  50,  51,  51,  51,  58,  64,  66,  66,  66,  67,  69,
        69,  69,  70,  71,  71,  71,  76,  76,  78,  78,  78,  87,  92,
        93,  94,  95,  96,  96, 105, 105, 106, 107, 107, 108, 110, 110,
       113, 114, 116, 116])

In [52]:
filtered_age = data[ age > 10 ]
filtered_age

array([[  8,  11, 178,   1, 110],
       [  9,  15, 144,   1, 159],
       [ 10,  16, 203,   2, 280],
       [ 11,  18, 127,   1, 214],
       [ 12,  19,  63,   2, 161],
       [ 13,  21, 190,   2, 157],
       [ 14,  23,  80,   2, 258],
       [ 15,  26, 130,   2, 253],
       [ 16,  30, 309,   1, 123],
       [ 17,  37, 306,   1, 149],
       [ 18,  37, 320,   1, 266],
       [ 19,  38,  62,   2, 263],
       [ 20,  38,  72,   2, 227],
       [ 21,  39,  54,   1, 181],
       [ 22,  40, 350,   1, 174],
       [ 23,  41,  81,   1, 237],
       [ 24,  42, 334,   1, 233],
       [ 25,  44, 226,   1, 209],
       [ 26,  46, 332,   1, 242],
       [ 27,  48, 318,   2, 154],
       [ 28,  50, 190,   1, 293],
       [ 29,  51,  57,   1, 294],
       [ 30,  51, 192,   2, 276],
       [ 31,  51, 315,   2, 255],
       [ 32,  58,  61,   1, 285],
       [ 33,  64, 145,   2, 125],
       [ 34,  66, 165,   1, 229],
       [ 35,  66, 215,   2, 264],
       [ 36,  66, 255,   1, 187],
       [ 37,  

#### Key arguments

* arr: The NumPy array being indexed
* start: Starting index for slice
    * Integer or None to start from beginning
* stop: Ending index for slice
    * Integer or None to go to end
* step: Step size for slice
    * Integer
* column_index: Index of column to select
    * Integer index or string column name
* single_index: Single index for selecting one element
    * Integer index

In [ ]:
arr[start:stop:step, column_index] 

arr[single_index, column_index]

In [58]:
filtered_age[1:15:2]

array([[  9,  15, 144,   1, 159],
       [ 11,  18, 127,   1, 214],
       [ 13,  21, 190,   2, 157],
       [ 15,  26, 130,   2, 253],
       [ 17,  37, 306,   1, 149],
       [ 19,  38,  62,   2, 263],
       [ 21,  39,  54,   1, 181]])